a=int(input("Enter a number: "))
b=input("Enter name: ")
c=float(input("Enter float number: "))
list1 = [a,b,c]
print(list1)
d=input("Enter a name: ")
list1.insert(1,d)
print(list1)
e=int(input("Enter another number: "))
list1.append(e)
print(list1)