a=input("Enter a string: ")
b=int(input("Enter a number: "))
c=input("Enter a character: ")
d=bool(input("Enter boolean value: "))
e=float(input("Enter decimal value: "))
list=[a,b,c,d,e]
print(list[::-1])
print(list[2::])
print(list[1:4:])
print(list[-3::])